### ISSUE TITLE
键盘fixed定位，z-index没办法设置

### ISSUE THREAD

**Issue by Chryseis** [LiuuY/vehicle-plate-keyboard#11]
键盘fixed定位，z-index没办法设置，建议加个z-index参数，或者直接z-index默认层级设高

**Comment by LiuuY** [comment]
@Chryseis  键盘由一个 `<div id="license-keyboard-box"></div>` 包裹，你可以通过这个 id 设置样式。
不过后续这个 id 会改为由 props 传入。

**Comment by LiuuY** [comment]
#10 同样是样式自定义的需求

**Comment by LiuuY** [comment]
@Chryseis 0.8.0 版本移除了 SASS/CSS Module，你可以自定义样式了。
