### ISSUE TITLE
安装后无法使用

### ISSUE THREAD

**Issue by SCLGIS** [LiuuY/vehicle-plate-keyboard#15]
Cannot find module './types'.  TS2307

    1 | import * as React from 'react';
    2 | import './style.scss';
  > 3 | import { KeyboardProps } from './types';
      |                               ^
    4 | declare const LicenseKeyboard: React.MemoExoticComponent<(props: KeyboardProps) => React.ReactPortal>;
    5 | export default LicenseKeyboard;

**Comment by LiuuY** [comment]
请给出复现步骤。

**Comment by SCLGIS** [comment]
react +ts  项目

第一步：yarn add vehicle-plate-keyboard；

第二步：
import LicenseKeyboard from 'vehicle-plate-keyboard';
import 'vehicle-plate-keyboard/dist/main.css';
 
第三步编译报错了：
Cannot find module './types'.  TS2307

    1 | import * as React from 'react';
    2 | import './style.scss';
  > 3 | import { KeyboardProps } from './types';
      |                               ^
    4 | declare const LicenseKeyboard: React.MemoExoticComponent<(props: KeyboardProps) => React.ReactPortal>;
    5 | export default LicenseKeyboard;

**Comment by SCLGIS** [comment]
> 请给出复现步骤。

react +ts 项目

第一步：yarn add vehicle-plate-keyboard；

第二步：
import LicenseKeyboard from 'vehicle-plate-keyboard';
import 'vehicle-plate-keyboard/dist/main.css';

第三步编译报错了：
Cannot find module './types'. TS2307

1 | import * as React from 'react';
2 | import './style.scss';
3 | import { KeyboardProps } from './types';
| ^
4 | declare const LicenseKeyboard: React.MemoExoticComponent<(props: KeyboardProps) => React.ReactPortal>;
5 | export default LicenseKeyboard;

**Comment by LiuuY** [comment]
能给一个 codesandbox 的例子么？我这边无法复现。

**Comment by LiuuY** [comment]
或者看下这个可以的：https://codesandbox.io/s/vehicle-plate-keyboard-demo-xxdlv

**Comment by SCLGIS** [comment]
> 能给一个 codesandbox 的例子么？我这边无法复现。

是我ts配置的问题吗，我这边引入和安装  都和你的demo一样的  可是就是在ts检验的时候 编译不过去。

**Comment by SCLGIS** [comment]
> 或者看下这个可以的：https://codesandbox.io/s/vehicle-plate-keyboard-demo-xxdlv

我的 "typescript": "~3.7.2", 这个版本的， 我看你的是3.3.3

**Comment by SCLGIS** [comment]
> > 或者看下这个可以的：https://codesandbox.io/s/vehicle-plate-keyboard-demo-xxdlv
> 
> 我的 "typescript": "~3.7.2", 这个版本的， 我看你的是3.3.3

刚才把你的demo里面的typescript"换成: "~3.7.2"  也编译不过去

**Comment by LiuuY** [comment]
"typescript": "~3.7.2" 可以的：https://codesandbox.io/s/vehicle-plate-keyboard-demo-forked-y0s5l?file=/package.json

**Comment by SCLGIS** [comment]
> "typescript": "~3.7.2" 可以的：https://codesandbox.io/s/vehicle-plate-keyboard-demo-forked-y0s5l?file=/package.json

我刚才把
import * as React from 'react';
import './style.scss';
// import { KeyboardProps } from './types';
declare const LicenseKeyboard: React.MemoExoticComponent<(
  props: any
) => React.ReactPortal>;
export default LicenseKeyboard;


import * as React from 'react';
// import { KeyboardCellProps } from './types';
declare const KeyboardCell: React.MemoExoticComponent<(
  props: any
) => JSX.Element>;
export default KeyboardCell;


注释掉换成any
// import { KeyboardProps } from './types';
// import { KeyboardCellProps } from './types';
  props: any

就能编译通过， 我这边一直提示没'./types' 模块。

**Comment by SCLGIS** [comment]
> "typescript": "~3.7.2" 可以的：https://codesandbox.io/s/vehicle-plate-keyboard-demo-forked-y0s5l?file=/package.json

是我这边使用的问题吗？

**Comment by LiuuY** [comment]
我今晚发布一个新版本。

**Comment by LiuuY** [comment]
@SCLGIS 0.8.1 版本可以试试。

**Comment by SCLGIS** [comment]
> @SCLGIS 0.8.1 版本可以试试。

好的 感谢。

**Comment by SCLGIS** [comment]
> 我今晚发布一个新版本。

好的 感谢。

**Comment by SCLGIS** [comment]
> 我今晚发布一个新版本。

刚才试了下提示：
JSX element type 'LicenseKeyboard' does not have any construct or call signatures.

**Comment by LiuuY** [comment]
> > 我今晚发布一个新版本。
> 
> 刚才试了下提示：
> JSX element type 'LicenseKeyboard' does not have any construct or call signatures.

可以把你的工程发到 GitHub 上么？

**Comment by SCLGIS** [comment]
> > > 我今晚发布一个新版本。
> > 
> > 
> > 刚才试了下提示：
> > JSX element type 'LicenseKeyboard' does not have any construct or call signatures.
> 
> 可以把你的工程发到 GitHub 上么？

公司的项目，我这边不好发上去。

**Comment by LiuuY** [comment]
好的，我晚点再看下。

**Comment by SCLGIS** [comment]
> 好的，我晚点再看下。

好的 谢谢啦

**Comment by SCLGIS** [comment]
> 好的，我晚点再看下。

好的

**Comment by SCLGIS** [comment]
你好 我想咨询一下  我每次输入结束后  关闭弹框后  再次打开还会出现上一次的输入状态   我想每次关闭后  进行组件销毁   可以支持么

**Comment by LiuuY** [comment]
0.8.3 版本，例子：https://github.com/LiuuY/vehicle-plate-keyboard-example/tree/main/typescript，我试了 yarn build 可以的。

**Comment by SCLGIS** [comment]
> 0.8.3 版本，[例子](https://github.com/LiuuY/vehicle-plate-keyboard-example/tree/main/typescript)，
> 我试了 yarn build 可以的。

好的
