### ISSUE TITLE
好像不支持ref绑定  获取的值一直为null

### ISSUE THREAD

**Issue by DSsarah** [LiuuY/vehicle-plate-keyboard#22]

**Comment by LiuuY** [comment]
能在 codesandbox 或者其他平台给一个复现么？

**Comment by DSsarah** [comment]
![image](https://user-images.githubusercontent.com/30138451/126031040-f528da3c-6b13-4697-9418-e8cdbe22d005.png)

**Comment by LiuuY** [comment]
不支持。
[You may not use the ref attribute on function components because they don’t have instances.](https://reactjs.org/docs/refs-and-the-dom.html#accessing-refs)
