### ISSUE TITLE
如果能加上正则校验就好了

### ISSUE THREAD

**Issue by duzliang** [LiuuY/vehicle-plate-keyboard#6]

**Comment by LiuuY** [comment]
可以举个使用的例子么？

**Comment by duzliang** [comment]
@LiuuY 普通车牌号没问题，新能源车牌号格式没有校验，比如D，F字母在首尾或者末尾

**Comment by LiuuY** [comment]
@duzliang [0.7.0 版本](https://github.com/LiuuY/vehicle-plate-keyboard/blob/master/CHANGELOG.md#070)增加了新能源车牌号格式的校验
